# Pandas Learning Notes

This notebook keeps **your original practice code exactly as written**. I have only added notes before each code cell explaining what that cell does.

In [1]:
import pandas as pd

## 1. Import Pandas

**What this cell does:** Imports the Pandas library and gives it the short name `pd`. We use `pd` to access Pandas functions such as `read_csv()`.

In [5]:
df= pd.read_csv("orders.csv")

## 2. Read the CSV file

**What this cell does:** Reads `orders.csv` and stores the data in a Pandas DataFrame called `df`.

- `pd.read_csv()` → reads a CSV file.
- `df` → variable containing the DataFrame.

In [6]:
print(df)

    OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas Müller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country
0   1200.0  2024-06-01     Yes           USA
1    150.0  2024-06-03      No        Canada
2    300.0  2024-06-04     Yes           UAE
3     45.0  2024-06-05     Yes     Singapore
4     80.0  2024-06-06      No        Mexico
5      5.0  2024-06-07     Yes           UAE
6    450.0  2024-06-08     Yes            UK
7    220.0  2024-06-09      No   South Korea
8      1.5  2024-06-10     Yes         Italy
9     35.0  2024-06-11     Yes         Japan
10    85.0  2024-06-12     Yes        France
11   180.0  2024-06-13      No         India
12    12.0  2024-06-14     Yes     Australia
13    25.0  2024-06-15     Yes         Spain
14   280.0  2024-06-16      No         China
15     8.0  2024-06-17     Yes         Egypt
16    45.0  2024-06-18     Yes        Poland
17    65.0  2024-06-19      No           USA
18    15.0  2024-06-20     Yes         Japan
19   120.0  2024-06-21     Yes  Saudi Arabia
20     3.5  2024-06-22      No        Canada
21    95.0  2024-06-23     Yes        Brazil
22    35.0  2024-06-24     Yes       Germany
23     4.0  2024-06-25      No      Pakistan
24    28.0  2024-06-26     Yes        Sweden
25    75.0  2024-06-27     Yes        France
26    22.0  2024-06-28      No     Argentina
27     2.5  2024-06-29     Yes        Russia
28   110.0  2024-06-30     Yes   South Korea
29    18.0  2024-07-01      No         Italy
30    32.0  2024-07-02     Yes       Morocco
31   140.0  2024-07-03     Yes       Germany
32    42.0  2024-07-04      No      Colombia
33     0.8  2024-07-05     Yes           USA
34    55.0  2024-07-06     Yes         Japan
35    68.0  2024-07-07      No            UK
36   125.0  2024-07-08     Yes      Portugal
37    28.0  2024-07-09     Yes          Iran
38    18.0  2024-07-10      No   South Korea
39    35.0  2024-07-11     Yes       Ukraine

## 3. Display the complete DataFrame

**What this cell does:** Prints the complete contents of `df` to the output.

In [7]:
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

## 4. View the first 5 rows

**What this cell does:** `head()` displays the first 5 rows of the DataFrame by default.

You can also use `df.head(10)` to display the first 10 rows.

In [8]:
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

## 5. View the last 5 rows

**What this cell does:** `tail()` displays the last 5 rows of the DataFrame by default.

You can also use `df.tail(10)` to display the last 10 rows.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     object
 2   Product       40 non-null     object
 3   Category      40 non-null     object
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     object
 7   Shipped       40 non-null     object
 8   Country       40 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 2.9+ KB

## 6. Understand DataFrame information

**What this cell does:** `info()` gives structural information about the DataFrame, including the number of rows, columns, non-null values, data types, and memory usage.

In [10]:
df.describe()

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

## 7. Get statistical summary

**What this cell does:** `describe()` gives descriptive statistics for numeric columns, such as `count`, `mean`, `std`, `min`, quartiles, and `max`.

In [13]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

## 8. Get column names

**What this cell does:** `df.columns` returns the names of all columns in the DataFrame.

In [14]:
df.index

RangeIndex(start=0, stop=40, step=1)

## 9. Get the DataFrame index

**What this cell does:** `df.index` shows the index information. Here the default index starts at 0 and increases by 1.

In [15]:
df['Country']

0              USA
1           Canada
2              UAE
3        Singapore
4           Mexico
5              UAE
6               UK
7      South Korea
8            Italy
9            Japan
10          France
11           India
12       Australia
13           Spain
14           China
15           Egypt
16          Poland
17             USA
18           Japan
19    Saudi Arabia
20          Canada
21          Brazil
22         Germany
23        Pakistan
24          Sweden
25          France
26       Argentina
27          Russia
28     South Korea
29           Italy
30         Morocco
31         Germany
32        Colombia
33             USA
34           Japan
35              UK
36        Portugal
37            Iran
38     South Korea
39         Ukraine
Name: Country, dtype: object

## 10. Select one column

**What this cell does:** Selects only the `Country` column.

The result is a Pandas **Series**.

In [16]:
len(df['Country'])

40

## 11. Find the number of values

**What this cell does:** `len()` counts how many values are present in the selected `Country` Series.

In [17]:
set(df['Country'])

{'Argentina',
 'Australia',
 'Brazil',
 'Canada',
 'China',
 'Colombia',
 'Egypt',
 'France',
 'Germany',
 'India',
 'Iran',
 'Italy',
 'Japan',
 'Mexico',
 'Morocco',
 'Pakistan',
 'Poland',
 'Portugal',
 'Russia',
 'Saudi Arabia',
 'Singapore',
 'South Korea',
 'Spain',
 'Sweden',
 'UAE',
 'UK',
 'USA',
 'Ukraine'}

## 12. Get unique values

**What this cell does:** `set()` converts the values from the `Country` column into a Python set, so duplicate country names are removed.

In [21]:
df[['Country', 'Product','Category','Quantity']]

         Country                Product     Category  Quantity
0            USA                 Laptop  Electronics         1
1         Canada             Headphones  Electronics         2
2            UAE           Office Chair    Furniture         1
3      Singapore              Desk Lamp    Furniture         3
4         Mexico               Keyboard  Electronics         2
5            UAE               Notebook   Stationery         5
6             UK          Standing Desk    Furniture         1
7    South Korea                Monitor  Electronics         2
8          Italy                    Pen   Stationery        10
9          Japan                  Mouse  Electronics         1
10        France                 Webcam  Electronics         1
11         India           File Cabinet    Furniture         2
12     Australia                Stapler   Stationery         3
13         Spain              USB Drive  Electronics         5
14         China              Bookshelf    Furniture         1
15         Egypt          Printer Paper   Stationery        20
16        Poland         Wireless Mouse  Electronics         2
17           USA         Desk Organizer    Furniture         1
18         Japan             Calculator  Electronics         1
19  Saudi Arabia             Whiteboard    Furniture         1
20        Canada           Highlighters   Stationery         8
21        Brazil      Bluetooth Speaker  Electronics         1
22       Germany           Office Plant    Furniture         2
23      Pakistan           Sticky Notes   Stationery        15
24        Sweden           Tablet Stand  Electronics         1
25        France         Paper Shredder  Electronics         1
26     Argentina         Desk Chair Mat    Furniture         1
27        Russia           Binder Clips   Stationery        12
28   South Korea      Wireless Keyboard  Electronics         1
29         Italy          Desk Calendar    Furniture         1
30       Morocco                USB Hub  Electronics         1
31       Germany       Document Scanner  Electronics         1
32      Colombia  Desk Drawer Organizer    Furniture         1
33           USA            Index Cards   Stationery       100
34         Japan          Monitor Stand  Electronics         1
35            UK     Desk Lamp with USB    Furniture         1
36      Portugal       Wireless Earbuds  Electronics         1
37          Iran               Desk Pad    Furniture         1
38   South Korea            Power Strip  Electronics         2
39       Ukraine             Desk Clock    Furniture         1

## 13. Select multiple columns

**What this cell does:** Selects only these four columns:

- `Country`
- `Product`
- `Category`
- `Quantity`

Double square brackets `[[...]]` are used when selecting multiple columns.

In [24]:
df.iloc[0]

OrderID                1001
CustomerName     John Smith
Product              Laptop
Category        Electronics
Quantity                  1
Price                1200.0
OrderDate        2024-06-01
Shipped                 Yes
Country                 USA
Name: 0, dtype: object

## 14. Select the first row using iloc

**What this cell does:** `iloc[0]` selects the row at **integer position 0**, which is the first row.

In [25]:
list(df.iloc[0])

[np.int64(1001),
 'John Smith',
 'Laptop',
 'Electronics',
 np.int64(1),
 np.float64(1200.0),
 '2024-06-01',
 'Yes',
 'USA']

## 15. Convert the first row to a list

**What this cell does:** First `df.iloc[0]` selects the first row. `list()` then converts that row into a normal Python list containing its values.

In [27]:
df.iloc[0][2]

/tmp/ipykernel_2800/2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Laptop'

## 16. Select a value using row and column position

**What this cell does:** `df.iloc[0][2]` first selects row position `0`, then selects the value at position `2` from that row.

So this is **position-based indexing**.

In [28]:
df.iloc[0]['Country']

'USA'

## 17. Select a value using a column name

**What this cell does:** Selects the first row using `iloc[0]`, then accesses the `Country` value using the column name.

This combines row selection with column-name selection.

In [38]:
df[df["Category"]=="Electronics"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

## 18. Filter rows by one condition

**What this cell does:** Keeps only rows where the `Category` column is equal to `Electronics`.

Pattern:
`df[condition]`

This is called **Boolean filtering**.

In [42]:
df[(df["Category"]=="Electronics") & (df["Country"] == "USA")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

## 19. Filter using AND (`&`)

**What this cell does:** Keeps rows where **both** conditions are true:

1. `Category` is `Electronics`
2. `Country` is `USA`

`&` means **AND** in Pandas Boolean filtering.

In [43]:
df[(df["Category"]=="Electronics") | (df["Country"] == "USA")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

## 20. Filter using OR (`|`)

**What this cell does:** Keeps rows where **at least one** condition is true:

1. `Category` is `Electronics`, OR
2. `Country` is `USA`

`|` means **OR** in Pandas Boolean filtering.

In [47]:
df[df['Price'] > 200]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China

## 21. Filter using a numeric condition

**What this cell does:** Selects rows where `Price` is greater than `200`.

In [48]:
df[df['CustomerName'].str.startswith("A")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

## 22. Filter strings that start with a value

**What this cell does:** `.str.startswith("A")` checks whether each `CustomerName` starts with the letter `A`.

The rows satisfying the condition are returned.

In [50]:
df[df['CustomerName'].str.endswith('n')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK

## 23. Filter strings that end with a value

**What this cell does:** `.str.endswith('n')` checks whether each `CustomerName` ends with the letter `n`.

In [54]:
df[df['Country'].isin(["USA", "UK", "Germany", "Sweden"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK

## 24. Filter using isin()

**What this cell does:** `isin([...])` checks whether each country belongs to the given list of countries.

Here it keeps rows whose country is one of: `USA`, `UK`, `Germany`, or `Sweden`.

In [55]:
df[~df['Country'].isin(["USA", "UK", "Germany", "Sweden"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

## 25. Reverse an isin() condition

**What this cell does:** `~` reverses the Boolean condition.

So instead of selecting countries in the list, this selects countries **not** in the list.

In [61]:
df.loc[df['Country'] == "USA"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

## 26. Filter rows using loc

**What this cell does:** `.loc[...]` is label-based selection. Here it selects all rows where `Country` is `USA`.

In [62]:
df.loc[df['Country'] == "USA", 'Product']

0             Laptop
17    Desk Organizer
33       Index Cards
Name: Product, dtype: object

## 27. Select a column after filtering with loc

**What this cell does:** First filters rows where `Country` is `USA`, then selects only the `Product` column.

So the result contains the products ordered from USA.

In [65]:
df.loc[df['Country'] == "USA", 'Product']

0             Laptop
17    Desk Organizer
33       Index Cards
Name: Product, dtype: object

## 28. Same operation again

**What this cell does:** This cell contains the same code as the previous cell. It again selects the `Product` values for rows where `Country` is `USA`.

In [66]:
df.loc[df['Country'] == "USA", 'Product'] = 'Laptop'

## 29. Update values using loc

**What this cell does:** Finds rows where `Country` is `USA` and changes their `Product` value to `Laptop`.

`.loc[condition, column] = value` can be used to update selected DataFrame values.

In [67]:
df.loc[df['Country'] == "USA", 'Product']

0     Laptop
17    Laptop
33    Laptop
Name: Product, dtype: object

## 30. Check the updated values

**What this cell does:** Runs the same USA + Product selection again so you can see the values after the update made in the previous cell.

In [69]:
df['Country'] = df['Country'].str.upper()
df['Country']

0              USA
1           CANADA
2              UAE
3        SINGAPORE
4           MEXICO
5              UAE
6               UK
7      SOUTH KOREA
8            ITALY
9            JAPAN
10          FRANCE
11           INDIA
12       AUSTRALIA
13           SPAIN
14           CHINA
15           EGYPT
16          POLAND
17             USA
18           JAPAN
19    SAUDI ARABIA
20          CANADA
21          BRAZIL
22         GERMANY
23        PAKISTAN
24          SWEDEN
25          FRANCE
26       ARGENTINA
27          RUSSIA
28     SOUTH KOREA
29           ITALY
30         MOROCCO
31         GERMANY
32        COLOMBIA
33             USA
34           JAPAN
35              UK
36        PORTUGAL
37            IRAN
38     SOUTH KOREA
39         UKRAINE
Name: Country, dtype: object

## 31. Convert Country values to uppercase

**What this cell does:** `.str.upper()` converts every string in the `Country` column to uppercase, and the result is assigned back to the same column.

The next line displays the updated column.

In [70]:
df=df.drop(38)
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,UKRAINE

## 32. Drop a row

**What this cell does:** `df.drop(38)` removes the row whose index is `38` and assigns the resulting DataFrame back to `df`.

The next line displays the last rows so you can check the result.

In [71]:
df.dropna()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
17,1018,Michael Brown,Laptop,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Laptop,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,UKRAINE

## 33. Remove rows containing missing values

**What this cell does:** `dropna()` returns a DataFrame with rows containing missing (`NaN`) values removed.

Because the result is not assigned back to `df`, this cell does **not permanently change `df`**.

In [72]:
df.fillna({"OrderId":0}, inplace=True)

## 34. Fill missing values

**What this cell does:** `fillna(..., inplace=True)` attempts to replace missing values in the specified column with `0` and modify `df` directly.

**Important:** Your dataset uses the column name `OrderID`, while this code uses `OrderId`. Keep the code exactly as you practiced it, but be aware that the capitalization/spelling does not match the shown column name.

In [74]:
df.rename(columns={"CustomerName": "CustName"}, inplace=True)
df

,OrderID,CustName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
17,1018,Michael Brown,Laptop,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Laptop,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,UKRAINE

## 35. Rename a column

**What this cell does:** Renames `CustomerName` to `CustName` and uses `inplace=True` so the change is made directly to `df`.

The next line displays the updated DataFrame.

In [76]:
df["Country"].value_counts()

Country
USA             3
JAPAN           3
UAE             2
CANADA          2
FRANCE          2
UK              2
ITALY           2
SOUTH KOREA     2
GERMANY         2
SINGAPORE       1
INDIA           1
MEXICO          1
AUSTRALIA       1
SPAIN           1
EGYPT           1
CHINA           1
POLAND          1
SAUDI ARABIA    1
BRAZIL          1
PAKISTAN        1
SWEDEN          1
ARGENTINA       1
RUSSIA          1
MOROCCO         1
COLOMBIA        1
PORTUGAL        1
IRAN            1
UKRAINE         1
Name: count, dtype: int64

## 36. Count values with value_counts()

**What this cell does:** Counts how many times each country appears in the `Country` column.

`value_counts()` is useful for finding the frequency of categorical values.

In [79]:
df.groupby("Country")["Price"].sum()

Country
ARGENTINA         22.0
AUSTRALIA         12.0
BRAZIL            95.0
CANADA           153.5
CHINA            280.0
COLOMBIA          42.0
EGYPT              8.0
FRANCE           160.0
GERMANY          175.0
INDIA            180.0
IRAN              28.0
ITALY             19.5
JAPAN            105.0
MEXICO            80.0
MOROCCO           32.0
PAKISTAN           4.0
POLAND            45.0
PORTUGAL         125.0
RUSSIA             2.5
SAUDI ARABIA     120.0
SINGAPORE         45.0
SOUTH KOREA      330.0
SPAIN             25.0
SWEDEN            28.0
UAE              305.0
UK               518.0
UKRAINE           35.0
USA             1265.8
Name: Price, dtype: float64

## 37. Group data and calculate a sum

**What this cell does:** Groups the DataFrame by `Country`, selects the `Price` column, and calculates the total `Price` for each country using `sum()`.

Pattern:
`groupby(column)[column_to_calculate].sum()`

In [86]:
df.sort_values("Price", ascending=True)

,OrderID,CustName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
33,1034,Alex Johnson,Laptop,Stationery,100,0.8,2024-07-05,Yes,USA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,UKRAINE
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
17,1018,Michael Brown,Laptop,Furniture,1,65.0,2024-06-19,No,USA
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA